INSERT INTO smn_cobranzas.smn_documento
(
	smn_documento_id,
	smn_documento_general_rf,
	smn_tipo_documento_id,
	doc_codigo,
	doc_descripcion,
	doc_afec_documento,
	doc_usa_moneda_alterna,
	doc_multiples_pagador,
	doc_estatus,
	doc_vigencia,
	doc_idioma,
	doc_usuario,
	doc_fecha_registro,
	doc_hora
)
VALUES
(
	${seq:currval@smn_cobranzas.seq_smn_documento},
	${fld:smn_documento_general_rf},
	${fld:smn_tipo_documento_id},
	${fld:doc_codigo},
	${fld:doc_descripcion},
	${fld:doc_afec_documento},
	${fld:doc_usa_moneda_alterna},
	${fld:doc_multiples_pagador},
	${fld:doc_estatus},
	${fld:doc_vigencia},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
