select
		smn_cobranzas.smn_mov_det_descuento.smn_mov_documento_cob_det_id,
	smn_cobranzas.smn_mov_det_descuento.smn_codigo_descuento_id,
	smn_cobranzas.smn_mov_det_descuento.mds_porcentaje,
	smn_cobranzas.smn_mov_det_descuento.mds_base,
	smn_cobranzas.smn_mov_det_descuento.mds_monto_descuento_ml,
	smn_cobranzas.smn_mov_det_descuento.smn_moneda_rf,
	smn_cobranzas.smn_mov_det_descuento.smn_tasa_rf,
	smn_cobranzas.smn_mov_det_descuento.mds_monto_descuento_ma,
	smn_cobranzas.smn_mov_det_descuento.mds_fecha_registro
from
	smn_cobranzas.smn_mov_det_descuento 
where
	smn_cobranzas.smn_mov_det_descuento.smn_mov_det_descuento_id = ${fld:id}
