select
		smn_cobranzas.smn_relacion_envio_cobranza.smn_relacion_envio_cobranza_id,
select
		smn_cobranzas.smn_relacion_envio_cobranza.smn_relacion_envio_cobranza_id,
select
		smn_cobranzas.smn_relacion_envio_cobranza.smn_relacion_envio_cobranza_id,
	smn_cobranzas.smn_relacion_envio_cobranza.smn_entidad_rf,
	smn_cobranzas.smn_relacion_envio_cobranza.rec_numero,
	smn_cobranzas.smn_relacion_envio_cobranza.smn_cliente_rf,
	smn_cobranzas.smn_relacion_envio_cobranza.rec_monto_ml,
	smn_cobranzas.smn_relacion_envio_cobranza.rec_monto_ma,
	smn_cobranzas.smn_relacion_envio_cobranza.rec_estatus,
	smn_cobranzas.smn_relacion_envio_cobranza.rec_fecha_registro
	
from
	smn_cobranzas.smn_relacion_envio_cobranza
